### PR TITLE
React base

### PR DESCRIPTION
**Pull request by jcrock7723**
Pull request after the addition of column sort functionality utilizing the useSortBy function of react-table!

### CODE REVIEW

**Comment by jcrock7723** [comment]
> Is there a reason for having a BostonHousing copy.csv ?

Absolutely not. I was utilizing it for testing and just slipped up during cleaning. I meant to delete it before the pull request. My apologies

**Comment by jcrock7723** [comment]
I removed the test data file.

**Comment by claesmk** [comment]
Looks good thanks for cleaning up the test file!

**Comment by jcrock7723** [comment]
> 
> 
> Looks good thanks for cleaning up the test file!

No problem. Happy to do it, thank you!

**Pull request merged**
